name: Code Scans with SFDX Scanner

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - UAT
    paths:
      - "force-app/**"

jobs:
  code-scan:
    runs-on: ubuntu-latest
    name: "Code Scan"
    steps:
        - name: SFDX Scan Pull Request
          uses: mitchspano/sfdx-scan-pull-request@v0.1.16
            
